### ISSUE TITLE
Add hello world program 

### ISSUE THREAD

**Issue by shreyraj2002** [shreyraj2002/hello-world#2]
Add Hello world program in any language which you love!! "This is only for beginners"

**Comment by Shrey2002** [comment]
i want to do this in C++

**Comment by shreyraj2002** [comment]
> i want to do this in C++

This issue is open to all!!

**Comment by Sheetal-Nayak** [comment]
Can I add a java "Hello World" file?

**Comment by shreyraj2002** [comment]
> Can I add a java "Hello World" file?

yes! this open to all

**Comment by Srinjoycode** [comment]
I have added the hello world program for the javascript language could you please merge my pull request

**Comment by rishav311** [comment]
I want to do this

**Comment by Anushree176** [comment]
Added code for Java and Python. Please review my PR #11

**Comment by chiillax** [comment]
I want to do this in C++.
