### ISSUE TITLE
Bubblesort Code

### ISSUE THREAD

**Issue by shreyraj2002** [shreyraj2002/hello-world#9]
Don't make the PRs directly firstly ask for assign!
and write the language you want to opt!
Add the bubble sort code in any language in the respective folders

**Comment by MayankAg20** [comment]
Could you please assign me for this task?

**Comment by shreyraj2002** [comment]
in which language you r creating PR?

**Comment by MayankAg20** [comment]
c++

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by Sheetal-Nayak** [comment]
Could you please assign me to do this task in java?

**Comment by shreyraj2002** [comment]
> Could you please assign me to do this task in java?

create a PR asap!

**Comment by Aathira123** [comment]
Could you please assign me to do this task in python ?

**Comment by Amulya-coder** [comment]
Could you assign me it for C .

**Comment by Sheetal-Nayak** [comment]
> > Could you please assign me to do this task in java?
> 
> create a PR asap!

Yes, I created a PR

**Comment by MayankAg20** [comment]
is this repository not participating in hacktoberfest?

**Comment by kokilgupta** [comment]
Could you assign it to me for c++

**Comment by MayankAg20** [comment]
Please make sure to add hacktoberfest config as it is currently showing this repo as not participating

**Comment by Alisha-Ahmed** [comment]
@shreyraj2002 Could you please assign me this to be done in C.

**Comment by AjayArvind2207** [comment]
could i please do this in python?
